package com.met.impilo.utils

object Constants {

    const val REF_PRODUCTS = "products"
    const val REF_PERSONAL_DATA = "personalData"
    const val REF_BODY_MEASUREMENTS = "bodyMeasurements"
    const val REF_DEMAND_COLLECTION = "demand_collection"
    const val REF_DEMAND = "demand"
    const val REF_USER_DATA = "userData"
    const val REF_ALL_MEALS = "allMeals"
    const val REF_MEALS = "meals"
    const val REF_MEALS_PRODUCTS = "mealsProducts"
    const val REF_USER_MEAL_SET = "mealSetInfo"
    const val RC_GOOGLE_SIGN_IN = 1
    const val ONLY_CONFIGURATION = "onlyConfiguration"

    const val LOGIN_REQUEST = 103
    const val CAMERA_REQUEST = 102
    const val MEAL_ID_REQUEST = "meal_id_request"
    const val MEAL_NAME_REQUEST = "meal_name_request"

    const val TRAPEZIUS_LEFT = "trapezius_left"
    const val TRAPEZIUS_RIGHT = "trapezius_right"
    const val SHOULDER_ANTERIOR_LEFT = "shoulder_anterior_head_left"
    const val SHOULDER_ANTERIOR_RIGHT = "shoulder_anterior_head_right"
    const val SHOULDER_MIDDLE_LEFT = "shoulder_middle_head_left"
    const val SHOULDER_MIDDLE_RIGHT = "shoulder_middle_head_right"
    const val SHOULDER_POSTERIOR_LEFT = "shoulder_posterior_head_left"
    const val SHOULDER_POSTERIOR_RIGHT = "shoulder_posterior_head_right"
    const val TERES_MINOR_LEFT = "teres_minor_left"
    const val TERES_MINOR_RIGHT = "teres_minor_right"
    const val TERES_MAJOR_LEFT = "teres_major_left"
    const val TERES_MAJOR_RIGHT = "teres_major_right"
    const val ERACTOR_SPINAE_LEFT = "eractor_spinae_left"
    const val ERACTOR_SPINAE_RIGHT = "eractor_spinae_right"
    const val GLUTE_LEFT = "glute_left"
    const val GLUTE_RIGHT = "glute_right"
    const val TRICEPS_LONG_LEFT = "triceps_long_head_left"
    const val TRICEPS_LONG_RIGHT = "triceps_long_head_right"
    const val TRICEPS_LATERAL_LEFT = "triceps_lateral_head_left"
    const val TRICEPS_LATERAL_RIGHT = "triceps_lateral_head_right"
    const val TRICEPS_MEDIAL_LEFT = "triceps_medial_head_left"
    const val TRICEPS_MEDIAL_RIGHT = "triceps_medial_head_right"
    const val CHEST_LEFT = "chest_left"
    const val CHEST_RIGHT = "chest_right"
    const val BICEPS_LONG_LEFT = "biceps_long_head_left"
    const val BICEPS_LONG_RIGHT = "biceps_long_head_right"
    const val BICEPS_SHORT_LEFT = "biceps_short_head_left"
    const val BICEPS_SHORT_RIGHT = "biceps_short_head_right"
    const val FOREARM_EXTERNAL_LEFT = "forearm_left_external"
    const val FOREARM_EXTERNAL_RIGHT = "forearm_right_external"
    const val FOREARM_INTERNAL_LEFT = "forearm_left_internal"
    const val FOREARM_INTERNAL_RIGHT = "forearm_right_internal"
    const val FOREARM_EXTENSIR_LEFT = "forearm_extensor_carpi_ulnaris_left"
    const val FOREARM_EXTENSIR_RIGHT = "forearm_extensor_carpi_ulnaris_right"
    const val FOREARM_REXOR_LEFT = "forearm_rexor_carpi_ulnaris_left"
    const val FOREARM_REXOR_RIGHT = "forearm_rexor_carpi_ulnaris_right"
    const val FOREARM_BRACHIORADIALIS_LEFT = "forearm_brachioradialis_left"
    const val FOREARM_BRACHIORADIALIS_RIGHT = "forearm_brachioradialis_right"
    const val FOREARM_FLEXOR_LEFT = "forearm_flexor_carpi_radialis_left"
    const val FOREARM_FLEXOR_RIGHT = "forearm_flexor_carpi_radialis_right"
    const val LATISSIMUS_DORSI_LEFT = "latissimus_dorsi_left"
    const val LATISSIMUS_DORSI_RIGHT = "latissimus_dorsi_right"
    const val SERRATUS_ANTERIOR_X8 = "serratus_anterior"
    const val EXTERNAL_OBLIQUE_LEFT = "external_oblique_left"
    const val EXTERNAL_OBLIQUE_RIGHT = "external_oblique_right"
    const val ABS_X8 = "abs"
    const val THIGHS = "thighs"
    const val CALVES = "calves"
}